spring.application.name=kithub-backend

# --- YEN? BULUT VER?TABANI (NEON) AYARLARI ---
spring.datasource.url=jdbc:postgresql://ep-withered-art-ahhmbdql.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pbVGByO5A0UW
spring.datasource.driver-class-name=org.postgresql.Driver

# --- H?BERNATE AYARLARI ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090

# --- AP? VE YAPAY ZEKA AYARLARI ---
google.books.api.key=AIzaSyBc8pUUV_6LqK9mDaXBGyxgmt1bhc-bBqw

ollama.api.url=http://localhost:11434/api/generate
ollama.model=llama3

gemini.api.key=AIzaSyAA_DxsayyqoGT-3hv6OFsuc7CXfHcbJfY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=