spring.application.name=kithub-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/kithub
spring.datasource.username=cem
spring.datasource.password=kithub2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090